# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  transport: smtp
  username: 'sadeckyvit@gmail.com'
  password: 'klokanek55'
  disable_delivery: false
  delivery_addresses: ['sadeckyvit@gmail.com']
