# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  sdh:
    recipients:
    - 'sadeckyvit@gmail.com'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  #LISTENERS - flexibility for any web page
  user.listener:
    class: App\Listener\UserListener
    tags:
    - { name: kernel.event_listener, event: user.createPre }
    - { name: kernel.event_listener, event: user.createPost }
    - { name: kernel.event_listener, event: user.deletePre }
    - { name: kernel.event_listener, event: user.deletePost }

  subject.listener:
    class: App\Listener\SubjectListener
    tags:
    - { name: kernel.event_listener, event: subject.createPre }
    - { name: kernel.event_listener, event: subject.createPost }
    - { name: kernel.event_listener, event: subject.deletePre }
    - { name: kernel.event_listener, event: subject.deletePost }


  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
